name = "unofficialyoutube"
main = "dist/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[build]
command = "npm run build"

[observability]
enabled = true
